config/routes.rb
Rails.application.routes.draw do
  # get "user/new"
  # get "user/create"
  # get "user/show"
  resources :user
  get "sessions/create"

  root "user#index"

  get "signup", to: "user#new"
  post "signup", to: "user#new"

  get "login", to: "sessions#login"
  post "login",  to: "sessions#create"

  get "logout", to: "sessions#destroy"
  delete "logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [ :new, :create, :login ]

  def new
  end

  def login
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:success] = "You have successfully logged in"
        redirect_to root_path
    else
        flash.now[:error] = "There was something wrong with your login"
        render "new"
    end
  end

  def destroy
    session[:user_id] =nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
      if logged_in?
          flash[:error] = "You are already logged in"
          redirect_to root_path
      end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :require_user, only: [ :index, :show ]

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in?
        !!session[:user_id]
    end

    def current_user
      @current_user ||=User.find_by_id(session[:user_id]) if !!session[:user_id]
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-controller= "hi">
  <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="me-auto">
              <p class="text-white fs-4 pl-5">Rails Practice</p>
          </div>

          <div class='d-flex gap-4 right-4 me-4'>
              <%= form_with url: signup_path, method: :get, class: "d-inline" do %>
                <button type="submit" class="btn btn-primary">Sign up</button>
              <% end %>
              <% if logged_in? %>
                <%= form_with url: logout_path, method: :delete, class: "d-inline" do %>
                  <button type="submit" class="btn btn-primary">Logout</button>
                <% end %>
              <% else %>
                <%= form_with url: login_path, method: :get, class: "d-inline" do %>
                  <button type="submit" class="btn btn-primary">Login</button>
                <% end %>
              <% end %>
          </div>

      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Practice" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>


<%= form_for @user, url: signup_path do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  
  <%= f.label :password %>
  <%= f.password_field :password %>
  
  <%= f.submit "Sign Up" %>
<% end %>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>